/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { AutomationService } from "../automation.service";
import { AutomationCreateInput } from "./AutomationCreateInput";
import { Automation } from "./Automation";
import { AutomationFindManyArgs } from "./AutomationFindManyArgs";
import { AutomationWhereUniqueInput } from "./AutomationWhereUniqueInput";
import { AutomationUpdateInput } from "./AutomationUpdateInput";

export class AutomationControllerBase {
  constructor(protected readonly service: AutomationService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Automation })
  async createAutomation(
    @common.Body() data: AutomationCreateInput
  ): Promise<Automation> {
    return await this.service.createAutomation({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        actions: true,
        createdAt: true,
        id: true,
        trigger: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workflowName: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Automation] })
  @ApiNestedQuery(AutomationFindManyArgs)
  async automations(@common.Req() request: Request): Promise<Automation[]> {
    const args = plainToClass(AutomationFindManyArgs, request.query);
    return this.service.automations({
      ...args,
      select: {
        actions: true,
        createdAt: true,
        id: true,
        trigger: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workflowName: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Automation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async automation(
    @common.Param() params: AutomationWhereUniqueInput
  ): Promise<Automation | null> {
    const result = await this.service.automation({
      where: params,
      select: {
        actions: true,
        createdAt: true,
        id: true,
        trigger: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },

        workflowName: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Automation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateAutomation(
    @common.Param() params: AutomationWhereUniqueInput,
    @common.Body() data: AutomationUpdateInput
  ): Promise<Automation | null> {
    try {
      return await this.service.updateAutomation({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          actions: true,
          createdAt: true,
          id: true,
          trigger: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workflowName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Automation })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteAutomation(
    @common.Param() params: AutomationWhereUniqueInput
  ): Promise<Automation | null> {
    try {
      return await this.service.deleteAutomation({
        where: params,
        select: {
          actions: true,
          createdAt: true,
          id: true,
          trigger: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },

          workflowName: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
