/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AutomationCreateNestedManyWithoutUsersInput } from "./AutomationCreateNestedManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { IntegrationCreateNestedManyWithoutUsersInput } from "./IntegrationCreateNestedManyWithoutUsersInput";
import { ReminderCreateNestedManyWithoutUsersInput } from "./ReminderCreateNestedManyWithoutUsersInput";
import { TaskCreateNestedManyWithoutUsersInput } from "./TaskCreateNestedManyWithoutUsersInput";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: false,
    type: () => AutomationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AutomationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AutomationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  automations?: AutomationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => IntegrationCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => IntegrationCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => IntegrationCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  integrations?: IntegrationCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReminderCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReminderCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReminderCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  reminders?: ReminderCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TaskCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TaskCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TaskCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  tasks?: TaskCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserCreateInput as UserCreateInput };
