/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AutomationUpdateManyWithoutUsersInput } from "./AutomationUpdateManyWithoutUsersInput";
import { ValidateNested, IsOptional, IsString } from "class-validator";
import { Type } from "class-transformer";
import { IntegrationUpdateManyWithoutUsersInput } from "./IntegrationUpdateManyWithoutUsersInput";
import { ReminderUpdateManyWithoutUsersInput } from "./ReminderUpdateManyWithoutUsersInput";
import { TaskUpdateManyWithoutUsersInput } from "./TaskUpdateManyWithoutUsersInput";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AutomationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AutomationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AutomationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  automations?: AutomationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: () => IntegrationUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => IntegrationUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => IntegrationUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  integrations?: IntegrationUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string | null;

  @ApiProperty({
    required: false,
    type: () => ReminderUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => ReminderUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => ReminderUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  reminders?: ReminderUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => TaskUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TaskUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TaskUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tasks?: TaskUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string | null;
}

export { UserUpdateInput as UserUpdateInput };
